apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: dataprocess-bre-eventeval
  namespace: {{ .Values.namespace }}
spec:
  topic: sonarianalyzeentitytopic
  route: /businessruleeventeval
  pubsubname: sonariapubsub
scopes:
- sonaria-dataprocess-bre-dapr