kind: Secret
apiVersion: v1
metadata:
  name: registrysecret
  namespace: {{ .Values.namespace }}
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJsb3dyeWRldi5henVyZWNyLmlvIjp7InVzZXJuYW1lIjoiNWE4YzUxMGYtYzA3Zi00YWMxLTg5MTItZjBmZDlkMmYwMDQxIiwicGFzc3dvcmQiOiJzWlg3a2E4ZEpjZjBCME5Mdnl4MXFudDFsVEpmL0tJblZ6QjV4VGJVOThXWVhWS3R0dUgyV2c9PSIsImVtYWlsIjoiU2VydmljZVByaW5jaXBhbEBBenVyZVJNIiwiYXV0aCI6Ik5XRTRZelV4TUdZdFl6QTNaaTAwWVdNeExUZzVNVEl0WmpCbVpEbGtNbVl3TURReE9uTmFXRGRyWVRoa1NtTm1NRUl3VGt4MmVYZ3hjVzUwTVd4VVNtWXZTMGx1Vm5wQ05YaFVZbFU1T0ZkWldGWkxkSFIxU0RKWFp6MDkifX19
type: kubernetes.io/dockerconfigjson
